### PR TITLE
Incorrect user shown for Created version in Version History #9161

### LINKED ISSUE #9161: Incorrect user shown for Created version in Version History
When we artificially create a "Created" version in Version History, we incorrectly resolve user name. It should be exactly the same as on "Created by" line of the "Details" widget

### PR DESCRIPTION
**Pull request by ashklianko**
Forcing fetching of a creator's display name

### CODE REVIEW

File: modules/lib/src/main/resources/assets/js/app/dialog/CompareContentVersionsDialog.ts [hunk 1]
```diff
@@ -322,8 +328,16 @@ export class CompareContentVersionsDialog
...
+        const getContentVersions = new GetContentVersionsRequest(this.content.getContentId()).sendAndParse();
+        const getPrincipalByKey = new GetPrincipalsByKeysRequest([this.content.getContentSummary().getCreator()]).sendAndParse().catch(
+            (e) => {
+                DefaultErrorHandler.handle(e);
+                return [];
+            });
+
+        return Q.all([getContentVersions, getPrincipalByKey]).spread((result: GetContentVersionsResult, principals: Principal[]) => {
             this.versions = result.getContentVersions();
+            this.creatorDisplayName = principals[0]?.getDisplayName() ?? this.content.getContentSummary().getCreator().toString();
```
Comment (alansemenov) [inline modules/lib/src/main/resources/assets/js/app/dialog/CompareContentVersionsDialog.ts]: Could assign `this.content.getContentSummary().getCreator()` to a const to avoid calling it twice, on lines 332 and 340.

**Review by alansemenov — APPROVED** [review]
