### PR TITLE
Customize page is not working #7470

### LINKED ISSUE #7470: Customize page is not working
IMPORTANT: Use next.xp for rendering. 
Edit "Carrie Ann Moss" and and try to customize page. 
It will simply "freeze" with an overlay.

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

File: modules/lib/src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerForm.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ export class PageTemplateAndControllerForm
         super('page-template-and-controller-form');
 
         let fieldSet = new Fieldset();
-        fieldSet.add(new FormItemBuilder(selector).setLabel(i18n('field.page.template')).build());
+        fieldSet.add(new FormItemBuilder(selector).setLabel(i18n('field.page.renderer')).build());
```
Comment (alansemenov) [inline modules/lib/src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerForm.ts]: Why did we change this? No editor will ever understand what "renderer" is.

Comment (ashklianko) [reply modules/lib/src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerForm.ts]: 'template' is being shown over a dropdown even when controller is selected, thought about more common name

Comment (alansemenov) [reply modules/lib/src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerForm.ts]: That's how it's been for a very long time and no one complained. It could be "Template or controller" (but that's too long and technical). Let's roll it back to "Template".

Comment (ashklianko) [reply modules/lib/src/main/resources/assets/js/app/wizard/page/contextwindow/inspect/page/PageTemplateAndControllerForm.ts]: Ok!

**Review by alansemenov — APPROVED** [review]
