### PR TITLE
Fix highlight and scroll to the input from AI Dialog #8101

### LINKED ISSUE #8101: Fix highlight and scroll to the input from AI Dialog
Highlight and scroll to the element in AI dialog stopped working after removing 'data-path' attribute, need to implement a new approach for this behavior.

- Send corresponding events to Studio and do highlighting/scrolling from there.
- Item-set and option set option should also work

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

**Comment by ashklianko** [comment]
Requires https://github.com/enonic/app-ai-content-operator/pull/153

File: modules/lib/src/main/resources/assets/js/app/ai/ui/InteractionType.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export type InteractionType = 'click';
```
Comment (edloidas) [inline modules/lib/src/main/resources/assets/js/app/ai/ui/InteractionType.ts]: Not sure that it deserves to be in a separate file (even more so under `/ui`). We won't probably use it as import, so it can be just an inner type in AiContentOperatorInteractionEvent

File: modules/lib/src/main/resources/assets/js/app/ai/AI.ts [hunk 2]
```diff
@@ -238,6 +241,26 @@ export class AI {
         }
     };
 
+    private handleInteractionEvent = (event: AiContentOperatorInteractionEvent) => {
+        if (event.interaction === 'click') {
```
Comment (edloidas) [inline modules/lib/src/main/resources/assets/js/app/ai/AI.ts]: It's better to have switch here, because that's what you do, right? If you have switch without the `default` clause, it will show error, if you add new interaction, but forget to add the handler. So it's kinda handy, IMHO.

**Review by edloidas — CHANGES_REQUESTED** [review]

**Review by edloidas — APPROVED** [review]
