### PR TITLE
Publish button is blocked when an outbound reference is missing #8834

### LINKED ISSUE #8834: No warning is given in the Publishing wizard for missing outbound references
To reproduce:

1. Log in as a user who doesn't have Administrator role but can publish content
2. Create a content (A) with HtmlArea input
3. Add an image (content B) to the HtmlArea
4. Save A
5. Click "Mark as ready" on A and publish both A and B
6. Archive B (click "Ignore references" in the Archive dialog). B is now unpublished and archived.
7. Open A for edit, change something and save. It will change from "Published" to "Modified".
8. Сlick "Mark as Ready" for A again and try to republish it.

Bug: The "Publish" button is blocked because of a missing outbound reference (note the yellow warning notifying about this). Note that for a user with "Administrator" role this is not the case, most likely because user with this role has access to the "missing" node under /archive.

New expected behaviour:
1. The button should not be blocked if there are missing (archived OR deleted) outbound references for content to be published.
2. The yellow warning should still be shown.
3. The new behaviour should be consistent regardless of the role - Administrator should also get a warning about missing references.
4. If possible, change the warning message to "Outbound reference with id [...] not found".

Image

### PR DESCRIPTION
**Pull request by ashklianko**
- Showing and keeping a warning message with missing outbound dependencies until the dialog is open again or there was a click over the notification msg

### CODE REVIEW

**Comment by alansemenov** [comment]
Doesn't work with `publishingWizard.excludeDependencies = true` in the config

**Comment by ashklianko** [comment]
Updated

File: modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
+package com.enonic.xp.app.contentstudio.rest.resource.content;
+
+import com.enonic.xp.content.ContentIds;
+
+class OutboundDependenciesIds
```
Comment (vbradnitski) [inline modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java:5]:
```suggestion
final class OutboundDependenciesIds
```

File: modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+{
+    private final ContentIds existingOutboundIds;
+
+    private final ContentIds nonExistingOutboundIds;
+
+    public OutboundDependenciesIds( final ContentIds existingIds, final ContentIds nonExistingIds )
```
Comment (vbradnitski) [inline modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java]:
```suggestion
   OutboundDependenciesIds( final ContentIds existingIds, final ContentIds nonExistingIds )
```
no need in excessive `public` access level in non-public class

File: modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+    {
+        this.existingOutboundIds = existingIds;
+        this.nonExistingOutboundIds = nonExistingIds;
+    }
+
+    public ContentIds getExistingOutboundIds()
```
Comment (vbradnitski) [inline modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java]:
```suggestion
   ContentIds getExistingOutboundIds()
```

the same

File: modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+    {
+        return existingOutboundIds;
+    }
+
+    public ContentIds getNonExistingOutboundIds()
```
Comment (vbradnitski) [inline modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/OutboundDependenciesIds.java]:
```suggestion
   ContentIds getNonExistingOutboundIds()
```
the same

File: modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java [hunk 5]
```diff
@@ -697,7 +697,8 @@ public ResolvePublishContentResultJson resolvePublishContent( final ResolvePubli
             .isAllowedFor( ContextAccessor.current().getAuthInfo().getPrincipals(), Permission.PUBLISH );
 
         //Get all outbound dependencies for current requested and required
-        final ContentIds nextDependencies = this.getOutboundDependenciesIds( fullPublishList );
+        final OutboundDependenciesIds outboundDependenciesIds = this.getOutboundDependenciesIds( fullPublishList );
+        final ContentIds nextDependencies = outboundDependenciesIds.getExistingOutboundIds();
```
Comment (vbradnitski) [inline modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java]:
```suggestion
```

File: modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java [hunk 6]
```diff
@@ -738,10 +739,11 @@ public ResolvePublishContentResultJson resolvePublishContent( final ResolvePubli
             .setContainsNotReady( !notReadyContentIds.isEmpty() )
             .setNotReadyContents( notReadyContentIds )
             .setNextDependentContents( nextDependencies )
```
Comment (vbradnitski) [inline modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java]:
```suggestion
            .setNextDependentContents( outboundDependenciesIds.getExistingOutboundIds() )
```

File: modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java [hunk 7]
```diff
@@ -755,14 +757,19 @@ private ContentIds getOutboundDependenciesIds( final ContentIds contentIds )
         } ).flatMap( ContentIds::stream ).filter( id -> !contentIds.contains( ContentId.from( id ) ) ).collect( Collectors.toList() ) );
```
Comment (vbradnitski) [inline modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java]:
```suggestion
        } ).flatMap( ContentIds::stream ).filter( id -> !contentIds.contains( id ) ).collect( Collectors.toList() ) );
```

**Review by vbradnitski — CHANGES_REQUESTED** [review]

**Review by vbradnitski — APPROVED** [review]

**Review by alansemenov — APPROVED** [review]
