### PR TITLE
Fix improper usage of promise void returns #8680

### LINKED ISSUE #8680: Fix improper usage of promise void returns
The current codebase contains several instances of improper Promise usage where functions return `Q(null)`. These pattern result in the return type being inferred as `any` instead of `void`, which is problematic, especially as we move toward enabling TypeScript strict mode and eliminating any.

Additionally, there are unnecessary usages of `Q(null)`, `Q.resolve()` where simply calling `Q()` (or nothing at all) would suffice.

### PR DESCRIPTION
**Pull request by edloidas**
Further refactoring related to #8677 and #8679 fixes. 
Makes code a little bit secure by returning void explicitly, instead of any. Also removes invalid or redundant code, that is not type checked due to current TSConfig.

### CODE REVIEW

File: modules/lib/src/main/resources/assets/js/app/dialog/CompareWithPublishedVersionDialog.ts [hunk 1]
```diff
@@ -193,7 +193,7 @@ export class CompareWithPublishedVersionDialog
         if (updateDiff) {
             return this.displayDiff();
         } else {
-            return Q.resolve();
+            return Q();
```
Comment (ashklianko) [inline modules/lib/src/main/resources/assets/js/app/dialog/CompareWithPublishedVersionDialog.ts]: Same here, no need 'else'

File: modules/lib/src/main/resources/assets/js/app/dialog/CompareWithPublishedVersionDialog.ts [hunk 2]
```diff
@@ -183,7 +183,7 @@ export class CompareWithPublishedVersionDialog
         if (updateDiff) {
             return this.displayDiff();
         } else {
```
Comment (ashklianko) [inline modules/lib/src/main/resources/assets/js/app/dialog/CompareWithPublishedVersionDialog.ts]: Don't need 'else', can make it even simpler:

```
if (updateDiff) {
            return this.displayDiff();
        } 
       
 return Q();
        
```

File: modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts [hunk 3]
```diff
@@ -943,15 +942,15 @@ export class ContentWizardPanel
 
     private handleNonRenderablePage(): Q.Promise<void> {
         this.liveEditModel = null;
-        return Q.resolve();
+        return Q();
     }
 
     private unloadPage(): Q.Promise<void> {
```
Comment (ashklianko) [inline modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts]: No need in promise here at all

**Review by ashklianko — CHANGES_REQUESTED** [review]

File: modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts (hunk 3 above)
Comment (ashklianko) [reply modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts]: And in `unloadPage` too

**Review by alansemenov — APPROVED** [review]

**Review by ashklianko — APPROVED** [review]

**Review by pmi — APPROVED** [review]
