### PR TITLE
Enhance HtmlArea toolbar AI button #7453

### LINKED ISSUE #7453: Enhance HtmlArea toolbar AI button
Make Assistant icon in HtmlArea toolbar open Assistant dialog and insert mention

### LINKED ISSUE #7455: HtmlArea: focusing editor should insert mention into open Assistant dialog
Doesn't work now

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

**Comment by ashklianko** [comment]
Requires https://github.com/enonic/app-saga/issues/157

File: modules/lib/src/main/resources/assets/js/app/saga/event/outgoing/EnonicAiToggleDialogEvent.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
+import {Event} from '@enonic/lib-admin-ui/event/Event';
+import {ClassHelper} from '@enonic/lib-admin-ui/ClassHelper';
+
+export class EnonicAiToggleDialogEvent
```
Comment (edloidas) [inline modules/lib/src/main/resources/assets/js/app/saga/event/outgoing/EnonicAiToggleDialogEvent.ts]: Shouldn't it be "Open/Show", not "Toggle". Will it close the dialog as well? Not sure it's expected behaviour to close the Assistant from HtmlArea

Comment (ashklianko) [reply modules/lib/src/main/resources/assets/js/app/saga/event/outgoing/EnonicAiToggleDialogEvent.ts]: Agree, Iet's make it just open the dialog
